[tool.poetry]
version = "0.1.0"
name = ""
description = ""
readme = "README.md"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
